name: License Scanning for Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'python/requirements.txt'
      - 'python/pyproject.toml'
      - '.github/workflows/python.yml'

env:
  ALLOW_LICENSES: "MIT License;Apache Software License;BSD License"
  # IGNORE_PACKAGES: ""

jobs:
  scan:
    name: Scan for licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12"
      - name: Install pip-licenses
        run: pip install pip-licenses
      - name: Scan for licenses
        run: pip-licenses --allow-only="${{ env.ALLOW_LICENSES }}" # --ignore-packages="${{ env.IGNORE_PACKAGES }}"
